name: blood
description: A new Flutter application.

publish_to: 'none'
version: 1.0.2

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.6.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  google_sign_in: ^6.3.0
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2
  logger:
  json_annotation: ^4.9.0
  #  pretty_dio_logger: ^1.1.1
  connectivity_plus: ^6.1.3
  #  day_night_switch: ^0.0.2+1
  flare_loading: ^3.0.0
  flutter_svg: ^2.0.17
  date_time_picker: ^2.1.0
  nepali_date_picker: ^6.0.1
  go_router: ^14.8.1
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  freezed_annotation: ^3.0.0
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4

dependency_overrides:
  firebase_core_platform_interface: ^5.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/