name: blood
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.1
  firebase_auth: ^3.3.0
  google_sign_in: ^5.2.1
  shimmer: ^2.0.0
  google_fonts: ^2.1.0
  shared_preferences: ^2.0.9
  logger:
  json_annotation: ^4.4.0
#  pretty_dio_logger: ^1.1.1
  connectivity: ^3.0.6
#  day_night_switch: ^0.0.2+1
  flare_loading: ^3.0.0
  flutter_svg: ^1.0.0
  date_time_picker: ^2.1.0
#  nepali_date_picker: ^4.2.0+1
  go_router: ^2.5.2

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  freezed: ^1.0.0
  freezed_annotation: ^1.0.0
  flutter_lints: ^1.0.4
  json_serializable: ^6.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/