name: blood
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  state_notifier: ^0.5.0
  flutter_riverpod: ^0.5.1
  cloud_firestore: ^0.13.7
#  permission_handler: ^5.0.1+1
  firebase_messaging: ^6.0.16
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  shimmer: ^1.1.1
  google_fonts: ^1.1.0
  shared_preferences: ^0.5.8
  logger:
    git: https://github.com/sarbagyastha/logger
  pretty_dio_logger: ^1.1.1
  connectivity: ^0.4.9
  day_night_switch: ^0.0.2+1
  flare_loading: ^2.1.1
  freezed: ^0.11.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.1
  auto_route_generator: ^0.6.8

flutter:
  uses-material-design: true

  assets:
    - assets/